
call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree'
Plug 'joshdick/onedark.vim'
Plug 'python-mode/python-mode', { 'for': 'python', 'branch': 'develop' }

" Initialize plugin system
call plug#end()

let g:pymode_python = 'python3'
set relativenumber
colorscheme onedark
