set -g base-index 1

set -g default-terminal "screen-256color"
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"

# pane border
set -g pane-border-style fg='#6272a4'
set -g pane-active-border-style fg='#ff79c6'

# message text
set -g message-style bg='#121212',fg='#8be9fd'

set -g status-style bg='#121212',fg='#bd93f9'
set -g status-interval 1

#status left
# are we controlling tmux or the content of the panes?
set -g status-left '#[bg=#f8f8f2]#[fg=#282a36]#{?client_prefix,#[bg=#ff79c6],} '
#window status
set-window-option -g window-status-style fg='#bd93f9',bg=default
set-window-option -g window-status-current-style fg='#ff79c6',bg='#121212'

#set -g window-status-current-format "#[fg=#121212]#[bg=#bd93f9]#[fg=#f8f8f2]#[bg=#bd93f9] #I #W
#[fg=#bd93f9]#[bg=#121212]"
set -g window-status-format "#[fg=#f8f8f2]#[bg=#121212]#I #W #[fg=#121212] "

# status right
set -g status-right ''
